#include <stdio.h>
#include "ft_printf.h"

int main()
{
	ft_printf("                ==============    MAIN    ============\n");
	ft_printf ("1-----------------------------------\n");
	printf("%d\n", printf("%d", 0));
	printf("%d\n", ft_printf("%d", 0));

	ft_printf("2---------------------\n");

	printf("%d\n", printf("   printf |%d|%d|%d|\n", 115, -12547, 799));
	printf("%d\n", ft_printf("ft_printf |%d|%d|%d|\n", 115, -12547, 799));

	ft_printf("3----------------------\n");

	int mn = -2147483648;
	int mx = 2147483647; 
	printf("%d\n", printf("   printf |%d|%d|\n", mx, mn));
	printf("%d\n", ft_printf("ft_printf |%d|%d|\n", mx, mn));

	ft_printf("4----------------------\n");

	printf("%d\n", printf("   printf |%5d|\n", 5));
	printf("%d\n", ft_printf("ft_printf |%5d|\n", 5));

	ft_printf("5----------------------\n");

	printf("%d\n", printf("   printf |%5d|\n", 55555));
	printf("%d\n", ft_printf("ft_printf |%5d|\n", 55555));

	ft_printf("6----------------------\n");

	printf("%d\n", printf("   printf |%5d|\n", 100000));
	printf("%d\n", ft_printf("ft_printf |%5d|\n", 100000));

	ft_printf("7----------------------\n");
	printf("%d\n", printf("   printf |%10d|%10d|%10d|\n", 5, 12, 178));
	printf("%d\n", ft_printf("ft_printf |%10d|%10d|%10d|\n", 5, 12, 178));
	ft_printf("8----------------------\n");
	printf("%d\n", printf("   printf |%-20d|%-20d|\n", mx, mn));
	printf("%d\n", ft_printf("ft_printf |%-20d|%-20d|\n", mx, mn));
	ft_printf("9----------------------\n");
	printf("%d\n", printf("   printf |%-d|\n", 5));
	printf("%d\n", ft_printf("ft_printf |%-d|\n", 5));
	ft_printf("10----------------------\n");
	printf("%d\n", printf("   printf |%-10d|\n", 5));
	printf("%d\n", ft_printf("ft_printf |%-10d|\n", 5));
	ft_printf("11----------------------\n");
	printf("%d\n", printf("   printf |%5d|\n", 000000));
	printf("%d\n", ft_printf("ft_printf |%5d|\n", 000000));
	ft_printf("12----------------------\n");
	printf("%d\n", printf("   printf |%5d|\n", -5));
	printf("%d\n", ft_printf("ft_printf |%5d|\n", -5));
	ft_printf("13----------------------\n");
	printf("%d\n", printf("   printf |%-5d|\n", -5));
	printf("%d\n", ft_printf("ft_printf |%-5d|\n", -5));
	ft_printf("14----------------------\n");
	printf("%d\n", printf("   printf |%-d|\n", -5));
	printf("%d\n", ft_printf("ft_printf |%-d|\n", -5));
	ft_printf("15----------------------\n");

	printf("%d\n", printf("   printf |%05d|\n", 5));
	printf("%d\n", ft_printf("ft_printf |%05d|\n", 5));
	ft_printf("16----------------------\n");
	printf("%d\n", printf("   printf |%00005d|\n", 5));
	printf("%d\n", ft_printf("ft_printf |%00005d|\n", 5));
	ft_printf("17----------------------\n");
	printf("%d\n", printf("   printf |%050d|\n", 55215));
	printf("%d\n", ft_printf("ft_printf |%050d|\n", 55215));
	ft_printf("18----------------------\n");
	printf("%d\n", printf("   printf |%012d|\n", -5));
	printf("%d\n", ft_printf("ft_printf |%012d|\n", -5));
	ft_printf("19----------------------\n");
	printf("%d\n", printf("   printf |%015d|%015d|\n", mx, mn));
	printf("%d\n", ft_printf("ft_printf |%015d|%015d|\n", mx, mn));
	ft_printf("20----------------------\n");

	printf("%d\n", 	  printf("   printf |%0.6d|%0.6d|\n", -5, 5));
	printf("%d\n", ft_printf("ft_printf |%0.6d|%0.6d|\n", -5, 5));
	ft_printf("21----------------------\n");

	printf("%d\n",    printf("   printf |%5.5d|%5.5d|\n", 12, -12));
	printf("%d\n", ft_printf("ft_printf |%5.5d|%5.5d|\n", 12, -12));
	ft_printf("22----------------------\n");

	printf("%d\n",    printf("   printf |%5.5d|%5.5d|\n", 10324, -10324));
	printf("%d\n", ft_printf("ft_printf |%5.5d|%5.5d|\n", 10324, -10324));
	ft_printf("23----------------------\n");
	printf("%d\n",    printf("   printf |%6.5d|%6.5d|\n", 5, -5));
	printf("%d\n", ft_printf("ft_printf |%6.5d|%6.5d|\n", 5, -5));
	ft_printf("24----------------------\n");
	printf("%d\n",    printf("   printf |%6.5d|%6.5d|\n", 10255, -1025));
	printf("%d\n", ft_printf("ft_printf |%6.5d|%6.5d|\n", 10255, -1025));
	ft_printf("25----------------------\n");
	printf("%d\n",    printf("   printf |%8.5d|%8.3d|\n", 10255, -1025));
	printf("%d\n", ft_printf("ft_printf |%8.5d|%8.3d|\n", 10255, -1025));
	ft_printf("26----------------------\n");
	printf("%d\n",    printf("   printf |%-8.6d|%-8.6d|\n", 1025, -1025));
	printf("%d\n", ft_printf("ft_printf |%-8.6d|%-8.6d|\n", 1025, -1025));
	ft_printf("27----------------------\n");
	printf("%d\n",    printf("   printf |%06.5d|%06.5d|\n", 255, -025));
	printf("%d\n", ft_printf("ft_printf |%06.5d|%06.5d|\n", 255, -025));
	ft_printf("28----------------------\n");
	printf("%d\n",    printf("   printf |%-6.6d|%-6.6d|\n", 255, -255));
	printf("%d\n", ft_printf("ft_printf |%-6.6d|%-6.6d|\n", 255, -525));
	ft_printf("29----------------------\n");
	printf("%d\n",    printf("   printf |%-4.5d|%-4.5d|\n", 255, -025));
	printf("%d\n", ft_printf("ft_printf |%-4.5d|%-4.5d|\n", 255, -025));
	ft_printf("30----------------------\n");
	printf("%d\n",    printf("   printf |%-.5d|%-.5d|\n", 255, -025));
	printf("%d\n", ft_printf("ft_printf |%-.5d|%-.5d|\n", 255, -025));
	ft_printf("31----------------------\n");
	printf("%d\n",    printf("   printf |%-6.1d|%-6.1d|\n", 255, -025));
	printf("%d\n", ft_printf("ft_printf |%-6.1d|%-6.1d|\n", 255, -025));
	ft_printf("32----------------------\n");
	printf("%d\n",    printf("   printf |%06.5d|%06.5d|\n", 255, -025));
	printf("%d\n", ft_printf("ft_printf |%06.5d|%06.5d|\n", 255, -025));
	ft_printf("33----------------------\n");
	printf("%d\n",    printf("   printf |%02d|%02d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%02d|%02d|\n", 100, -100));
	ft_printf ("45-----------------------------------\n");
	printf("%d\n",    printf("   printf |%03d|%03d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%03d|%03d|\n", 100, -100));
	ft_printf ("46-----------------------------------\n");
	printf("%d\n",    printf("   printf |%03d|%03d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%03d|%03d|\n", 100, -100));
	ft_printf ("47-----------------------------------\n");
	printf("%d\n", 	  printf("   printf |%03d|%03d|\n", 255, -100));
	printf("%d\n", ft_printf("ft_printf |%03d|%03d|\n", 255, -100));
	ft_printf ("48-----------------------------------\n");
	printf("%d\n",    printf("   printf |%04d|%02d|\n", 0, 100));
	printf("%d\n", ft_printf("ft_printf |%04d|%02d|\n", 0, 100));
	ft_printf ("49-----------------------------------\n");
	printf("%d\n",    printf("   printf |%04d|%02d|\n", -0, -100));
	printf("%d\n", ft_printf("ft_printf |%04d|%02d|\n", -0, -100));
	ft_printf ("50-----------------------------------\n");
	printf("%d\n",    printf("   printf |a%01da|a%01da|\n", 0, -0));
	printf("%d\n", ft_printf("ft_printf |a%01da|a%01da|\n", 0, -0));
	ft_printf ("51-----------------------------------\n");
	printf("%d\n",    printf("   printf |%2.3d|%2.3d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%2.3d|%2.3d|\n", 100, -100));
	ft_printf ("52-----------------------------------\n");
	printf("%d\n",    printf("   printf |%3.3d|%3.3d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%3.3d|%3.3d|\n", 100, -100));
	ft_printf ("53-----------------------------------\n");
	printf("%d\n",    printf("   printf |a%3.3da|a%3.3da|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |a%3.3da|a%3.3da|\n", 100, -100));
	ft_printf ("54-----------------------------------\n");
	printf("%d\n",    printf("   printf |%4.3d|%4.3d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%4.3d|%4.3d|\n", 100, -100));
	ft_printf ("55-----------------------------------\n");
	printf("%d\n",    printf("   printf |%2.3d|%2.3d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%2.3d|%2.3d|\n", 100, -100));
	ft_printf ("56-----------------------------------\n");
	printf("%d\n",    printf("   printf |%4.3d|%4.3d|\n", 0, -1));
	printf("%d\n", ft_printf("ft_printf |%4.3d|%4.3d|\n", 0, -1));
	ft_printf ("57-----------------------------------\n");
	printf("%d\n",    printf("   printf |%1.3d|%1.3d|\n", 0, -1));
	printf("%d\n", ft_printf("ft_printf |%1.3d|%1.3d|\n", 0, -1));
	ft_printf ("58-----------------------------------\n");
	printf("%d\n",    printf("   printf |a%1.3da|a%1.3da|\n", 0, -1));
	printf("%d\n", ft_printf("ft_printf |a%1.3da|a%1.3da|\n", 0, -1));
	ft_printf ("59-----------------------------------\n");
	printf("%d\n",    printf("   printf |%2.0d|%2.0d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%2.0d|%2.0d|\n", 100, -100));
	ft_printf ("60-----------------------------------\n");
	printf("%d\n",    printf("   printf |%3.0d|%3.0d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%3.0d|%3.0d|\n", 100, -100));
	ft_printf ("61-----------------------------------\n");
	printf("%d\n",    printf("   printf |a%3.0da|a%3.0da|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |a%3.0da|a%3.0da|\n", 100, -100));
	ft_printf ("62-----------------------------------\n");
	printf("%d\n",    printf("   printf |%4.0d|%4.0d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%4.0d|%4.0d|\n", 100, -100));
	ft_printf ("63-----------------------------------\n");
	printf("%d\n",    printf("   printf |%4.0d|%4.0d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%4.0d|%4.0d|\n", 100, -100));
	ft_printf ("64-----------------------------------\n");
	printf("%d\n",    printf("   printf |%1.0d|%1.0d|\n", 1, -1));
	printf("%d\n", ft_printf("ft_printf |%1.0d|%1.0d|\n", 1, -1));
	ft_printf ("65-----------------------------------\n");
	printf("%d\n",    printf("   printf |%4.d|%4.d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%4.d|%4.d|\n", 100, -100));
	ft_printf ("66-----------------------------------\n");
	printf("%d\n",    printf("   printf |%2.d|%2.d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%2.d|%2.d|\n", 100, -100));
	   ft_printf ("67-----------------------------------\n");
	printf("%d\n",    printf("   printf |%3.d|%3.d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%3.d|%3.d|\n", 100, -100));
	   ft_printf ("68-----------------------------------\n");
	printf("%d\n",    printf("   printf |%4.d|%4.d|\n", 0, -1));
	printf("%d\n", ft_printf("ft_printf |%4.d|%4.d|\n", 0, -1));
	   ft_printf ("69-----------------------------------\n");
	printf("%d\n",    printf("   printf |%1.d|%1.d|\n", 0, -1));
	printf("%d\n", ft_printf("ft_printf |%1.d|%1.d|\n", 0, -1));
	   ft_printf ("70-----------------------------------\n");
	printf("%d\n",    printf("   printf |%1.0d|%1.0d|\n", 0, -0));
	printf("%d\n", ft_printf("ft_printf |%1.0d|%1.0d|\n", 0, -0));
	   ft_printf ("70.1-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-3.0d|%-1.0d|\n", 0, -0));
	printf("%d\n", ft_printf("ft_printf |%-3.0d|%-1.0d|\n", 0, -0));
	   ft_printf ("71-----------------------------------\n");
	printf("%d\n",    printf("   printf |%2.7d|%2.7d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%2.7d|%2.7d|\n", 100, -100));
	   ft_printf ("72-----------------------------------\n");
	printf("%d\n",    printf("   printf |%15.7d|%15.7d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%15.7d|%15.7d|\n", 100, -100));
	   ft_printf ("73-----------------------------------\n");
	printf("%d\n",    printf("   printf |a%3.7da|a%3.7da|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |a%3.7da|a%3.7da|\n", 100, -100));
	   ft_printf ("74-----------------------------------\n");
	printf("%d\n",    printf("   printf |%4.7d|%4.7d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%4.7d|%4.7d|\n", 100, -100));
	   ft_printf ("75-----------------------------------\n");
	printf("%d\n",    printf("   printf |%4.7d|%4.7d|\n", 0, -0));
	printf("%d\n", ft_printf("ft_printf |%4.7d|%4.7d|\n", 0, -0));
	   ft_printf ("76-----------------------------------\n");
	printf("%d\n",    printf("   printf |%1.7d|%1.7d|\n", 0, -0));
	printf("%d\n", ft_printf("ft_printf |%1.7d|%1.7d|\n", 0, -0));
	   ft_printf ("77-----------------------------------\n");
	printf("%d\n",    printf("   printf |a%1.7da|a%1.7da|\n", 0, -0));
	printf("%d\n", ft_printf("ft_printf |a%1.7da|a%1.7da|\n", 0, -0));
	   ft_printf ("78-----------------------------------\n");
	printf("%d\n",    printf("   printf |%1d|%1d|\n", 0, -0));
	printf("%d\n", ft_printf("ft_printf |%1d|%1d|\n", 0, -0));
	   ft_printf ("79-----------------------------------\n");
	printf("%d\n",    printf("   printf |a%1da|a%1da|\n", 0, -0));
	printf("%d\n", ft_printf("ft_printf |a%1da|a%1da|\n", 0, -0));
	   ft_printf ("80-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-2d|%-2d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%-2d|%-2d|\n", 100, -100));
	   ft_printf ("81-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-3d|%-3d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%-3d|%-3d|\n", 100, -100));
	   ft_printf ("82-----------------------------------\n");
	printf("%d\n",    printf("   printf |%4.0d|%4.0d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%4.0d|%4.0d|\n", 100, -100));
	   ft_printf ("83-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-4d|%-4d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%-4d|%-4d|\n", 100, -100));
	   ft_printf ("84-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-4d|%-4d|\n", 0, -0));
	printf("%d\n", ft_printf("ft_printf |%-4d|%-4d|\n", 0, -0));
	   ft_printf ("85-----------------------------------\n");
	printf("%d\n",    printf("   printf |a%-1da|a%-1da|\n", 0, -0));
	printf("%d\n", ft_printf("ft_printf |a%-1da|a%-1da|\n", 0, -0));
	   ft_printf ("86-----------------------------------\n");
	printf("%d\n",    printf("ft_printf |%.3d|%.3d|\n", 100, -100));
	printf("%d\n", ft_printf("   printf |%.3d|%.3d|\n", 100, -100));
	   ft_printf ("87-----------------------------------\n");
	printf("%d\n",    printf("   printf |%4.0d|%4.0d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%4.0d|%4.0d|\n", 100, -100));
	   ft_printf ("88-----------------------------------\n");
	printf("%d\n",    printf("   printf |%4.0d|%4.0d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%4.0d|%4.0d|\n", 100, -100));
	   ft_printf ("89-----------------------------------\n");
	printf("%d\n",    printf("   printf |%.7d|%.7d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%.7d|%.7d|\n", 100, -100));
	   ft_printf ("90-----------------------------------\n");
	printf("%d\n",    printf("   printf |%5.7d|%5.7d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%5.7d|%5.7d|\n", 100, -100));
	   ft_printf ("91-----------------------------------\n");
	printf("%d\n",    printf("   printf |%.d|%.d|\n", 100, -100));
	printf("%d\n", ft_printf("ft_printf |%.d|%.d|\n", 100, -100));
	   ft_printf ("92-----------------------------------\n");
	printf("%d\n",    printf("   printf |%.d|%.d|\n", 0, 0));
	printf("%d\n", ft_printf("ft_printf |%.d|%.d|\n", 0, -0));
	   ft_printf ("93-----------------------------------\n");
	printf("%d\n",    printf("   printf |%.d|%.d|\n", 1, -1));
	printf("%d\n", ft_printf("ft_printf |%.d|%.d|\n", 1, -1));
	   ft_printf ("94-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*d|%*d|\n", 1, 0, 0, 0));
	printf("%d\n", ft_printf("ft_printf |%*d|%*d|\n", 1, 0, 0, 0));
	   ft_printf ("94-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*d|%*d|\n", 1, 1, 1, -1));
	printf("%d\n", ft_printf("ft_printf |%*d|%*d|\n", 1, 1, 1, -1));
	   ft_printf ("96-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*d|%*d|\n", 5, 0, 5, 12));
	printf("%d\n", ft_printf("ft_printf |%*d|%*d|\n", 5, 0, 5, 12));
	   ft_printf ("97-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*d|%*d|\n", 5, 1, 5, -1));
	printf("%d\n", ft_printf("ft_printf |%*d|%*d|\n", 5, 1, 5, -1));
	   ft_printf ("98-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*d|%*d|\n", 10, 100, 10, -100));
	printf("%d\n", ft_printf("ft_printf |%*d|%*d|\n", 10, 100, 10, -100));
	   ft_printf ("99-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*d|%*d|\n", -5, 100, -5, -100));
	printf("%d\n", ft_printf("ft_printf |%*d|%*d|\n", -5, 100, -5, -100));
	   ft_printf ("100-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*d|%*d|\n", -10, 100000, -10, -100000));
	printf("%d\n", ft_printf("ft_printf |%*d|%*d|\n", -10, 100000, -10, -100000));
	   ft_printf ("101-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*d|%*d|\n", -15, 100000, -15, -100000));
	printf("%d\n", ft_printf("ft_printf |%*d|%*d|\n", -15, 100000, -15, -100000));
	   ft_printf ("102-----------------------------------\n");
	   
	   ft_printf ("103-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*d|%0*d|\n", 0, 0, 0, 1));
	printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n", 0, 0, 0, 1));
	   ft_printf ("104-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*d|%0*d|\n", 0, -1, 1, -1));
	printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n", 0, -1, 1, -1));
	   ft_printf ("105-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*d|%0*d|\n", 5, 1, 5, -1));
	printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n", 5, 1, 5, -1));
	   ft_printf ("106-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*d|%0*d|\n", 5, 0, 5, -0));
	printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n", 5, 0, 5, -0));
	   ft_printf ("107-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*d|%*d|\n",  1, 0, 1, 1));  
	printf("%d\n", ft_printf("ft_printf |%*d|%*d|\n",  1, 0, 1, 1));
       ft_printf ("103-----------------------------------\n");
    printf("%d\n",    printf("   printf |%0*d|%0*d|\n", 0, 0, 0, 1));
   	printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n", 0, 0, 0, 1));
   	   ft_printf ("104-----------------------------------\n");
   	printf("%d\n",    printf("   printf |%0*d|%0*d|\n", 0, -1, -1, -1));
   	printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n", 0, -1, -1, -1));
       ft_printf ("105-----------------------------------\n");
    printf("%d\n",    printf("   printf |%0*d|%0*d|\n", -5, 1, -5, -1));
    printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n", -5, 1, -5, -1));
       ft_printf ("106-----------------------------------\n");
    printf("%d\n",    printf("   printf |%0*d|%0*d|\n", -5, 0, -5, -0));
    printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n", -5, 0, -5, -0));
       ft_printf ("108-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*d|%0*d|\n",  5, 100, 5, -100));
	printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n",  5, 100, 5, -100));
       ft_printf ("109-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*d|%0*d|\n",  -5, 10100, -5, -1010));
	printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n",  -5, 10100, -5, -1010));
       ft_printf ("110-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*d|%0*d|\n",  3, 10012, 3, -10012));
	printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n",  3, 10012, 3, -10012));
       ft_printf ("111-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*d|%0*d|\n",  -3, 10012, -3, -10012));
	printf("%d\n", ft_printf("ft_printf |%0*d|%0*d|\n",  -3, 10012, -3, -10012));
       ft_printf ("112-----------------------------------\n");
    printf("%d\n",    printf("   printf |%.*d|%.*d|\n", 0, 0, 5, -1));
   	printf("%d\n", ft_printf("ft_printf |%.*d|%.*d|\n", 0, 0, 5, -1));
       ft_printf ("113-----------------------------------\n");
    printf("%d\n",    printf("   printf |%.*d|%.*d|\n", -5, 1, -5, -1));
    printf("%d\n", ft_printf("ft_printf |%.*d|%.*d|\n", -5, 1, -5, -1));
       ft_printf ("114-----------------------------------\n");
    printf("%d\n",    printf("   printf |%.*d|%.*d|\n", 5, 0, 5, -0));
    printf("%d\n", ft_printf("ft_printf |%.*d|%.*d|\n", 5, 0, 5, -0));
       ft_printf ("115-----------------------------------\n");
	printf("%d\n",    printf("   printf |%.*d|%.*d|\n",  5, 100, 5, -100));
	printf("%d\n", ft_printf("ft_printf |%.*d|%.*d|\n",  5, 100, 5, -100));
       ft_printf ("116-----------------------------------\n");
	printf("%d\n",    printf("   printf |%.*d|%.*d|\n",  -5, 10100, 15, -1010));
	printf("%d\n", ft_printf("ft_printf |%.*d|%.*d|\n",  -5, 10100, 15, -1010));
       ft_printf ("117-----------------------------------\n");
	printf("%d\n",    printf("   printf |%.*d|%.*d|\n",  3, 10012, -3, -10012));
	printf("%d\n", ft_printf("ft_printf |%.*d|%.*d|\n",  3, 10012, -3, -10012));
       ft_printf ("118-----------------------------------\n");
	printf("%d\n",    printf("   printf |%.*d|%.*d|\n",  0, 10012, 0, -10012));
	printf("%d\n", ft_printf("ft_printf |%.*d|%.*d|\n",  0, 10012, 0, -10012));
       ft_printf ("118-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*d|%-*d|\n",  -3, 10012, -3, -10012));
	printf("%d\n", ft_printf("ft_printf |%-*d|%-*d|\n",  -3, 10100, -3, -1010));
       ft_printf ("119-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*d|%-*d|\n",  5, 10012, 5, -10012));
	printf("%d\n", ft_printf("ft_printf |%-*d|%-*d|\n",  5, 10012, 5, -10012));
       ft_printf ("120-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*d|%-*d|\n",  -5, 10012, -5, -10012));
	printf("%d\n", ft_printf("ft_printf |%-*d|%-*d|\n",  -5, 10012, -5, -10012));
       ft_printf ("121-----------------------------------\n");
    printf("%d\n",    printf("   printf |%-*d|%-*d|\n", 0, 0, 0, 0));
   	printf("%d\n", ft_printf("ft_printf |%-*d|%-*d|\n", 0, 0, 0, 0));
       ft_printf ("122-----------------------------------\n");
    printf("%d\n",    printf("   printf |%-*d|%-*d|\n", -5, 1, -5, -1));
    printf("%d\n", ft_printf("ft_printf |%-*d|%-*d|\n", -5, 1, -5, -1));
       ft_printf ("123-----------------------------------\n");
    printf("%d\n",    printf("   printf |%-*d|%-*d|\n", 5, 0, 5, -0));
    printf("%d\n", ft_printf("ft_printf |%-*d|%-*d|\n", 5, 0, 5, -0));
       ft_printf ("124-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*d|%-*d|\n",  5, 100, 5, -100));
	printf("%d\n", ft_printf("ft_printf |%-*d|%-*d|\n",  5, 100, 5, -100));
       ft_printf ("125-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*d|%-*d|\n",  -5, 10100, 15, -1010));
	printf("%d\n", ft_printf("ft_printf |%-*d|%-*d|\n",  -5, 10100, 15, -1010));
       ft_printf ("126-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*d|%-*d|\n",  20, 10012, 20, -10012));
	printf("%d\n", ft_printf("ft_printf |%-*d|%-*d|\n",  20, 10012, 20, -10012));
       ft_printf ("127-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*d|%-*d|\n",  -20, 10012, -20, -10012));
	printf("%d\n", ft_printf("ft_printf |%-*d|%-*d|\n",  -20, 10012, -20, -10012));
       ft_printf ("128-----------------------------------\n");
	
	printf("%d\n",    printf("   printf |%0*.d|%0*.d|\n",  -3, 10012, -3, -10012));
	printf("%d\n", ft_printf("ft_printf |%0*.d|%0*.d|\n",  -3, 10100, -3, -1010));
       ft_printf ("129-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*.d|%0*.d|\n",  5, 10012, 5, -10012));
	printf("%d\n", ft_printf("ft_printf |%0*.d|%0*.d|\n",  5, 10012, 5, -10012));
       ft_printf ("130-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*.d|%0*.d|\n",  -5, 10012, -5, -10012));
	printf("%d\n", ft_printf("ft_printf |%0*.d|%0*.d|\n",  -5, 10012, -5, -10012));
       ft_printf ("131-----------------------------------\n");
    printf("%d\n",    printf("   printf |%0*.d|%0*.d|\n", 0, 0, 0, 0));
   	printf("%d\n", ft_printf("ft_printf |%0*.d|%0*.d|\n", 0, 0, 0, 0));
       ft_printf ("132-----------------------------------\n");
    printf("%d\n",    printf("   printf |%0*.d|%0*.d|\n", -5, 1, -5, -1));
    printf("%d\n", ft_printf("ft_printf |%0*.d|%0*.d|\n", -5, 1, -5, -1));
       ft_printf ("133-----------------------------------\n");
    printf("%d\n",    printf("   printf |%0*.d|%0*.d|\n", 5, 0, 5, -0));
    printf("%d\n", ft_printf("ft_printf |%0*.d|%0*.d|\n", 5, 0, 5, -0));
       ft_printf ("134-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*.d|%0*.d|\n",  5, 100, 5, -100));
	printf("%d\n", ft_printf("ft_printf |%0*.d|%0*.d|\n",  5, 100, 5, -100));
       ft_printf ("135-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*.d|%0*.d|\n",  -5, 10100, 15, -1010));
	printf("%d\n", ft_printf("ft_printf |%0*.d|%0*.d|\n",  -5, 10100, 15, -1010));
       ft_printf ("136-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*.d|%0*.d|\n",  20, 10012, 20, -10012));
	printf("%d\n", ft_printf("ft_printf |%0*.d|%0*.d|\n",  20, 10012, 20, -10012));
       ft_printf ("137-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*.d|%0*.d|\n",  -20, 10012, -20, -10012));
	printf("%d\n", ft_printf("ft_printf |%0*.d|%0*.d|\n",  -20, 10012, -20, -10012));
       ft_printf ("138-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*.d|%0*.d|\n",  -3, 10012, -3, -10012));
	printf("%d\n", ft_printf("ft_printf |%0*.d|%0*.d|\n",  -3, 10100, -3, -1010));
       ft_printf ("139-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*.d|%-*.d|\n",  5, 10012, 5, -10012));
	printf("%d\n", ft_printf("ft_printf |%-*.d|%-*.d|\n",  5, 10012, 5, -10012));
       ft_printf ("140-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*.d|%-*.d|\n",  -5, 10012, -5, -10012));
	printf("%d\n", ft_printf("ft_printf |%-*.d|%-*.d|\n",  -5, 10012, -5, -10012));
       ft_printf ("141-----------------------------------\n");
    printf("%d\n",    printf("   printf |%-*.d|%-*.d|\n", 0, 0, -2, 0));
   	printf("%d\n", ft_printf("ft_printf |%-*.d|%-*.d|\n", 0, 0, -2, 0));
       ft_printf ("142-----------------------------------\n");
    printf("%d\n",    printf("   printf |%-*.d|%-*.d|\n", -5, 1, -5, -1));
    printf("%d\n", ft_printf("ft_printf |%-*.d|%-*.d|\n", -5, 1, -5, -1));
       ft_printf ("143-----------------------------------\n");
    printf("%d\n",    printf("   printf |%-*.d|%-*.d|\n", 5, 0, 5, -0));
    printf("%d\n", ft_printf("ft_printf |%-*.d|%-*.d|\n", 5, 0, 5, -0));
       ft_printf ("144-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*.d|%-*.d|\n",  5, 100, 5, -100));
	printf("%d\n", ft_printf("ft_printf |%-*.d|%-*.d|\n",  5, 100, 5, -100));
       ft_printf ("145-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*.d|%-*.d|\n",  -5, 10100, 15, -1010));
	printf("%d\n", ft_printf("ft_printf |%-*.d|%-*.d|\n",  -5, 10100, 15, -1010));
       ft_printf ("146-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*.d|%-*.d|\n",  20, 10012, 20, -10012));
	printf("%d\n", ft_printf("ft_printf |%-*.d|%-*.d|\n",  20, 10012, 20, -10012));
       ft_printf ("147-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*.d|%-*.d|\n",  -20, 10012, -20, -10012));
	printf("%d\n", ft_printf("ft_printf |%-*.d|%-*.d|\n",  -20, 10012, -20, -10012));
		ft_printf ("149-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n", -1, 1, 5, 1, 1, -5));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n", 5, 5, 5, 5, 5, -5));
       ft_printf ("150-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n",  0, 0, 5, 0, 0, -5));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n",  0, 0, 5, 0, 0, -5));
       ft_printf ("151-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n",  -1, -1, 5, -1, -1, -5));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n",  -1, -1, 5, -1, -1, -5));
       ft_printf ("152-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n", -5, -5, 5, -5, -5, -5));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n", -5, -5, 5, -5, -5, -5));
       ft_printf ("153-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n", 2, 2, 500, 2, 2, -500));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n", 2, 2, 500, 2, 2, -500));
       ft_printf ("154-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n",  -2, -2, 500, -2, -2, -500));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n",  -2, -2, 500, -2, -2, -500));
       ft_printf ("155-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n",  5, 5, 0, 5, 5, 0));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n",  5, 5, 0, 5, 5, 0));
       ft_printf ("156-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n",  0, 0, 0, 0, 0, 5));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n",  0, 0, 0, 0, 0, 5));
       ft_printf ("157-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n",  5, 3, 5, 5, 3, -5));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n",  5, 3, 5, 5, 3, -5));
       ft_printf ("158-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n",  -5, 3, 5, -5, 3, -5));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n",  -5, 3, 5, -5, 3, -5));
       ft_printf ("159-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n",  3, 4, 5, 5, 4, -5));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n",  3, 4, 5, 3, 4, -5));
       ft_printf ("160-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n",  -2, 4, 5, -2, 4, -5));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n",  -2, 4, 5, -2, 4, -5));
       ft_printf ("161-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.*d|%*.*d|\n",  3, 2, 5000, 3, 2, -5000));
	printf("%d\n", ft_printf("ft_printf |%*.*d|%*.*d|\n",  3, 2, 5000, 3, 2, -5000));
       ft_printf ("162-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*.*d|%*.*d|\n",  5, 15, 50000, 5, 15, -50000));
	printf("%d\n", ft_printf("ft_printf |%0*.*d|%*.*d|\n",  5, 15, 50000, 5, 15, -50000));
       ft_printf ("163-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*.*d|%*.*d|\n", 15, 5, 500000, 15, 5, -500000));
	printf("%d\n", ft_printf("ft_printf |%0*.*d|%*.*d|\n", 15, 5, 500000, 15, 5, -500000));
       ft_printf ("164-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*.*d|%015.5d|\n", 15, -5, 50, 50));
	printf("%d\n", ft_printf("ft_printf |%0*.*d|%015.5d|\n", 15, -5, 50, 50));
       ft_printf ("165-----------------------------------\n");
	printf("%d\n",    printf("   printf |%*.10d|%*.10d|\n", 15, 50, 15, -50));
	printf("%d\n", ft_printf("ft_printf |%*.10d|%*.10d|\n", 15, 50, 15, -50));
       ft_printf ("165-----------------------------------\n");
	printf("%d\n",    printf("   printf |%012.*d|%012.*d|\n", 10, 50, 10, 50));
	printf("%d\n", ft_printf("ft_printf |%012.*d|%012.*d|\n", 10, 50, 10, 50));
       ft_printf ("165-----------------------------------\n");
	printf("%d\n",    printf("   printf |%-*.*d|\n", 0, 10, 50));
	printf("%d\n", ft_printf("ft_printf |%-*.*d|\n", 0, 10, 50));
       ft_printf ("169-----------------------------------\n");
	printf("%d\n",    printf("   printf |%0*.*d|%0*.*d|\n", 8, 5, 50, -8, 5, -50));
	printf("%d\n", ft_printf("ft_printf |%0*.*d|%0*.*d|\n", 8, 5, 50, -8, 5, -50));

	return 0;
 }
